import "jquery";
import "axios";
import "bootstrap";
import "twbs-pagination/jquery.twbsPagination";
import "datatables.net-bs4";
import "./jquery.autocomplete.min";
import "./customers";
import "./films";
import "./switch-btn";